version: "3.9"

services:

  postgres:

    image: postgres:17

    container_name: energy_dw_postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: energy_user
      POSTGRES_PASSWORD: energy_password
      POSTGRES_DB: energy_dw

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create_dim_time.sql:/docker-entrypoint-initdb.d/1_create_dim_time.sql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:

  postgres_data: